### ISSUE TITLE
Uncaught TypeError: Cannot read property 'memo_dir_path' of undefined

### ISSUE THREAD

**Issue by AbdealiLoKo** [tgfjt/atom-memolist#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [atom-memolist](https://github.com/tgfjt/atom-memolist) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'memo_dir_path' of undefined

```
At /home/ajk/.atom/packages/atom-memolist/lib/atom-memolist-show.coffee:9

TypeError: Cannot read property 'memo_dir_path' of undefined
  at AtomMemolistShow.module.exports.AtomMemolistShow.initialize (/home/ajk/.atom/packages/atom-memolist/lib/atom-memolist-show.coffee:9:40)
  at AtomMemolistShow.View (/opt/atom/resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
  at AtomMemolistShow.SelectListView (/opt/atom/resources/app/src/select-list-view.js:16:51)
  at new AtomMemolistShow (/home/ajk/.atom/packages/atom-memolist/lib/atom-memolist-show.coffee:6:3)
  at Object.module.exports.show (/home/ajk/.atom/packages/atom-memolist/lib/atom-memolist.coffee:10:25)
  at atom-workspace.<anonymous> (/home/ajk/.atom/packages/atom-memolist/lib/atom-memolist.coffee:7:60)
  at atom-workspace.handler (/opt/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at /opt/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/atom/resources/app/src/window-event-handler.js:167:20)

```
### Commands

```
     -30:00.0 atom-memolist:toggle (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "node_modules"
    ],
    "disabledPackages": [
      "metrics",
      "spell-check",
      "editorconfig",
      "linter",
      "release-notes",
      "bookmarks",
      "open-on-github",
      "markdown-preview",
      "background-tips",
      "git-diff",
      "styleguide",
      "welcome",
      "file-explorer",
      "archive-view",
      "git-control",
      "tree-ignore",
      "atom-terminal",
      "terminal-status",
      "term2",
      "autocomplete-plus-async"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-memolist, v0.1.1
autocomplete-clang, v0.6.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
language-lisp, v0.1.1
notebook, v0.4.0
playlist, v0.1.7

# Dev
No dev packages
```

/cc @atom/core

**Comment by tgfjt** [comment]
@AbdealiJK 
Did you set path(`memo_dir_path`) in ~/.atom/config.cson?

This is my setting on Mac OSX.

```
  'atom-memolist':
    'memo_dir_path': '/Users/tgfjt/Dropbox/memo'
```

**Comment by tgfjt** [comment]
@AbdealiJK 
fell free to re-open when you get this error!
